cmake_minimum_required(VERSION 4.0)
project(Leetcode)

set(CMAKE_CXX_STANDARD 14)

add_executable(Leetcode
        Graphs/BFS.cpp
        Graphs/DFS.cpp
        Graphs/GraphPractise.cpp
        01Matrix.cpp
        2sum.cpp
        3integerSum.cpp
        add2Numbers.cpp
        BalanceArray.cpp
        Balanced_BT.cpp
        BestTimetoBuyandSellStock.cpp
        BinarySearch.cpp
        BinaryStep.cpp
        Brainpower[2140].cpp
        bst_traversals.cpp
        BT_Construction.cpp
        BT_RightSIdeView.cpp
        check_for_SortedRotated_array.cpp
        ClearDIgits.cpp
        ClimbingStairs.cpp
        CodeChef.cpp
        CoinChange.cpp
        CombinationSum.cpp
        CombinationSum2.cpp
        ConcatinatedDivisibilty.cpp
        ContainsDublicate.cpp
        ContainsDuplicate_LL.cpp
        CopyLLRandomPointer.cpp
        CountIslandsDivByk.cpp
        CycleDetectionGraph.cpp
        Daily_temp.cpp
        DecodeWays.cpp
        DetectAndRemove_LLCycle.cpp
        diameter.cpp
        EncodeDecode.cpp
        FibonacciNumber.cpp
        FloodFill.cpp
        good_node_BST.cpp
        goodCaption.cpp
        GroupAnagram.cpp
        health.cpp
        HouseRobber.cpp
        HouseRobber2.cpp
        IncreasingSubarray.cpp
        intToRoman.cpp
        invert_BT.cpp
        isAnagram.cpp
        Ispalindrome.cpp
        KPointClosestToOrigin.cpp
        kth_smallest_BST.cpp
        KthLargestInStream_Heaps.cpp
        KthLargetInArray.cpp
        Land&WaterSlide.cpp
        LargestIncreasingSubsequence.cpp
        LastStone.cpp
        LetterCombination.cpp
        lever_order_display.cpp
        LL_cycle.cpp
        Longest_substring_without_repeating.cpp
        LongestConsecutiveSequence.cpp
        LongestPalindromeString.cpp
        lowest_common_ancestor_BST.cpp
        markpoints.cpp
        max_pathSum.cpp
        MaxAreaofIsland.cpp
        MaximumValueofanOrderedTriplet.cpp
        MaxProductSubarray.cpp
        MaxSubarraySum.cpp
        MaxWater.cpp
        medianOfarray.cpp
        Merge_two_sortedLL.cpp
        mergeSortedArray.cpp
        MinClimbingStairs.cpp
        moveZeros.cpp
        NetwrokRecoveryPathways.cpp
        NQueens.cpp
        Nqueens.cpp
        NumberOfColouredCells.cpp
        NumberOfIslands.cpp
        NumberOfProvinces.cpp
        OddEvenLL.cpp
        PalindromePartitioning.cpp
        PalindromicSubstring.cpp
        PartitionEqualSubsets.cpp
        PeakIndex.cpp
        peakIndexMountain.cpp
        permutation.cpp
        plusOne.cpp
        polish_eval.cpp
        ProductOfarrayExcludingSelf.cpp
        remove_nth_node_from_last.cpp
        removeDublicates.cpp
        removeDuplicates2.cpp
        removeElement.cpp
        RemovingAllSubstring.cpp
        Reorder_LL.cpp
        reverse_LL.cpp
        reverseInt.cpp
        ReverseNodeInKGroup.cpp
        romanToint.cpp
        RotateArray.cpp
        RottenOranges.cpp
        same_tree.cpp
        Search_2D_matrix.cpp
        Searching_in_rotated_sorted_array.cpp
        SearchInsertpos.cpp
        SentenceSorting.cpp
        SerialiseDeserialsise.cpp
        SortColours.cpp
        SplitArrayByPrime.cpp
        Sqrt.cpp
        SquaresOfsortedArray.cpp
        StableMountain.cpp
        Subsets.cpp
        subsets2.cpp
        subtree.cpp
        SuperHero.cpp
        SurroundedRegions.cpp
        TaskScheduler.cpp
        topKFrequent.cpp
        trappingRainWater.cpp
        TupleWithSameProduct.cpp
        UniquePaths.cpp
        valid_pair_in_string.cpp
        validParenthesis.cpp
        WordBreak.cpp
        WordSearch.cpp)
